import { GoogleGenAI } from "@google/genai";

function delay(ms: number) {
  return new Promise((res) => setTimeout(res, ms));
}

// Define types for Gemini response
interface GeminiCandidatePart {
  text?: string;
}

interface GeminiCandidateContent {
  parts?: GeminiCandidatePart[];
}

interface GeminiCandidate {
  content?: GeminiCandidateContent & { role?: string };
}

interface GeminiResponse {
  output_text?: string;
  text?: string;
  temperature?: number;
  response?: { text?: () => string };
  candidates?: GeminiCandidate[];
  result?: { content?: { text?: string } }[];
}

export async function callGemini(
  prompt: string,
  retries = 3,
  initialDelay = 1000
): Promise<string> {
  console.log("🚀 ~ callGemini ~ prompt:", prompt);

  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    return `Mock response (no API key): ${prompt.slice(0, 200)}${
      prompt.length > 200 ? "..." : ""
    }`;
  }

  const ai = new GoogleGenAI({ apiKey });
  const DEFAULT_MODEL = process.env.GEMINI_MODEL || "gemini-2.5-flash";

  let attempt = 0;
  let delayMs = initialDelay;

  while (attempt < retries) {
    try {
      const response = (await ai.models.generateContent({
        model: DEFAULT_MODEL,
        contents: [{ text: prompt }],
        temperature: 0.3,
        topK: 40,
        topP: 0.9,
        maxOutputTokens: 800,
      } as any)) as GeminiResponse;

      console.log("Raw Gemini response:", JSON.stringify(response, null, 2));

      // ===== Robust parsing =====
      let text: string | undefined;

      // 1. Top-level properties
      text = response.output_text || response.text;

      // 2. response.text function
      if (!text && response.response?.text) {
        text = response.response.text();
      }

      // 3. candidates -> content -> parts
      if (!text && Array.isArray(response.candidates)) {
        const candidate = response.candidates[0];
        if (
          candidate?.content?.parts &&
          Array.isArray(candidate.content.parts)
        ) {
          text = candidate.content.parts.map((p) => p.text ?? "").join("\n");
        } else if (candidate?.content?.role) {
          // fallback: candidate exists but has no parts
          text = `[Candidate exists but no text generated]`;
        }
      }

      // 4. fallback: result array
      if (!text && response.result?.[0]?.content?.text) {
        text = response.result[0].content.text;
      }

      // 5. final fallback if still no text
      if (!text) {
        text = "[No answer generated by Gemini]";
      }

      return sanitizeOutput(text);
    } catch (error: any) {
      attempt++;
      const status = error?.status || error?.code;

      if ((status === 503 || status === "UNAVAILABLE") && attempt < retries) {
        console.warn(
          `Gemini unavailable (attempt ${attempt}/${retries}). Retrying in ${delayMs}ms...`
        );
        await delay(delayMs);
        delayMs *= 2;
      } else {
        const message = error?.message || String(error);
        console.error("Gemini SDK error:", error);
        throw new Error(`Failed to generate response: ${message}`);
      }
    }
  }

  throw new Error("Gemini service unavailable after multiple retries.");
}

/**
 * sanitizeOutput - remove duplicated halves/lines and dedupe similar bullets
 */
function sanitizeOutput(raw: string): string {
  const collapseDuplicateHalves = (s: string): string => {
    const compact = s.replace(/\s+/g, " ").trim();
    const m = compact.match(/^(.+?)\s*\1+$/);
    return m?.[1]?.trim() ?? s;
  };

  const lines = raw.split("\n");
  const seen = new Set<string>();
  const cleaned: string[] = [];
  for (let i = 0; i < lines.length; i++) {
    let line = lines[i] ?? "";
    if (i > 0 && line.trim() === (lines[i - 1] ?? "").trim()) continue;
    line = collapseDuplicateHalves(line);
    const normalized = line
      .replace(/https?:\/\/\S+/gi, "")
      .replace(/^[-*\d\.\)\s]+/, "")
      .replace(/\s+/g, " ")
      .toLowerCase()
      .trim();
    if (!normalized) {
      cleaned.push(line);
      continue;
    }
    if (seen.has(normalized)) continue;
    seen.add(normalized);
    cleaned.push(line);
  }
  return cleaned.join("\n");
}
